// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmUtGp0I6EY2Q4iKfIDLE6FGuhBVJXZcc',
    appId: '1:589990143464:web:f20c945aab4db31ddeb05d',
    messagingSenderId: '589990143464',
    projectId: 'challenge1-a46a6',
    authDomain: 'challenge1-a46a6.firebaseapp.com',
    storageBucket: 'challenge1-a46a6.firebasestorage.app',
    measurementId: 'G-XHQRC0VDDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfuErggK2NUI4Vh7llIZmIR6LJ19U9uoQ',
    appId: '1:589990143464:android:22c354218a862bd5deb05d',
    messagingSenderId: '589990143464',
    projectId: 'challenge1-a46a6',
    storageBucket: 'challenge1-a46a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZS-VxJJpm-qZ0MQE03Eb3IO8cpEP1Gbo',
    appId: '1:589990143464:ios:69c21faa4dfa368adeb05d',
    messagingSenderId: '589990143464',
    projectId: 'challenge1-a46a6',
    storageBucket: 'challenge1-a46a6.firebasestorage.app',
    iosClientId: '589990143464-opqnn3dnn5or5cohas96l89lpjad3dtp.apps.googleusercontent.com',
    iosBundleId: 'com.example.challenge1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZS-VxJJpm-qZ0MQE03Eb3IO8cpEP1Gbo',
    appId: '1:589990143464:ios:69c21faa4dfa368adeb05d',
    messagingSenderId: '589990143464',
    projectId: 'challenge1-a46a6',
    storageBucket: 'challenge1-a46a6.firebasestorage.app',
    iosClientId: '589990143464-opqnn3dnn5or5cohas96l89lpjad3dtp.apps.googleusercontent.com',
    iosBundleId: 'com.example.challenge1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmUtGp0I6EY2Q4iKfIDLE6FGuhBVJXZcc',
    appId: '1:589990143464:web:d80020e26ee4d72ddeb05d',
    messagingSenderId: '589990143464',
    projectId: 'challenge1-a46a6',
    authDomain: 'challenge1-a46a6.firebaseapp.com',
    storageBucket: 'challenge1-a46a6.firebasestorage.app',
    measurementId: 'G-DR56YRRZSM',
  );
}
